  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: backend-api
    namespace: crud-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: backend-api
    template:
      metadata:
        labels:
          app: backend-api
      spec:
        containers:
          - name: backend-api
            image: final_assignment-backend:latest
            imagePullPolicy: Never
            env:
              - name: db_address
                value: db
              - name: db_username
                value: postgres
              - name: db_name
                value: postgres
              - name: db_password
                valueFrom:
                  secretKeyRef:
                    name: db-password
                    key: password
            ports:
              - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: crud-app
  labels:
    app: backend-api
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: backend-api
  type: ClusterIP
